version: "3.9"
services:
  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=escout
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@database:5432/escout?sslmode=disable
    depends_on:
      - database
    entrypoint:
      [
        "/app/wait-for.sh",
        "database:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]

networks:
  escout-network:
    driver: bridge