// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type PriceChange struct {
	ID        int64     `json:"id"`
	ProductID int64     `json:"product_id"`
	Price     float64   `json:"price"`
	CreatedAt time.Time `json:"created_at"`
}

type Product struct {
	ID                int64     `json:"id"`
	UserID            int64     `json:"user_id"`
	Name              string    `json:"name"`
	Link              string    `json:"link"`
	BasePrice         float64   `json:"base_price"`
	PercentageChange  float64   `json:"percentage_change"`
	TrackingFrequency int32     `json:"tracking_frequency"`
	CronJobID         int64     `json:"cron_job_id"`
	IsActive          bool      `json:"is_active"`
	CreatedAt         time.Time `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}
