// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: price_changes.sql

package db

import (
	"context"
	"time"
)

const createPriceChange = `-- name: CreatePriceChange :one
INSERT INTO price_changes (product_id, price, created_at) VALUES ($1, $2, $3) RETURNING id, product_id, price, created_at
`

type CreatePriceChangeParams struct {
	ProductID int64     `json:"product_id"`
	Price     float64   `json:"price"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreatePriceChange(ctx context.Context, arg CreatePriceChangeParams) (PriceChange, error) {
	row := q.db.QueryRow(ctx, createPriceChange, arg.ProductID, arg.Price, arg.CreatedAt)
	var i PriceChange
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const deletePriceChange = `-- name: DeletePriceChange :exec
DELETE FROM price_changes WHERE id = $1
`

func (q *Queries) DeletePriceChange(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePriceChange, id)
	return err
}

const getPriceChangesByPriceRange = `-- name: GetPriceChangesByPriceRange :many
SELECT id, product_id, price, created_at FROM price_changes WHERE price BETWEEN $1 AND $2 ORDER BY created_at DESC LIMIT $3 OFFSET $4
`

type GetPriceChangesByPriceRangeParams struct {
	Price   float64 `json:"price"`
	Price_2 float64 `json:"price_2"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

func (q *Queries) GetPriceChangesByPriceRange(ctx context.Context, arg GetPriceChangesByPriceRangeParams) ([]PriceChange, error) {
	rows, err := q.db.Query(ctx, getPriceChangesByPriceRange,
		arg.Price,
		arg.Price_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceChange{}
	for rows.Next() {
		var i PriceChange
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPriceChangesByTimeRange = `-- name: GetPriceChangesByTimeRange :many
SELECT id, product_id, price, created_at FROM price_changes WHERE created_at BETWEEN $1 AND $2 ORDER BY created_at DESC LIMIT $3 OFFSET $4
`

type GetPriceChangesByTimeRangeParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) GetPriceChangesByTimeRange(ctx context.Context, arg GetPriceChangesByTimeRangeParams) ([]PriceChange, error) {
	rows, err := q.db.Query(ctx, getPriceChangesByTimeRange,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceChange{}
	for rows.Next() {
		var i PriceChange
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPriceChangesForUserAndProduct = `-- name: GetPriceChangesForUserAndProduct :many
SELECT pc.id, pc.product_id, pc.price, pc.created_at
FROM price_changes pc
JOIN products p ON pc.product_id = p.id
JOIN users u ON u.id = p.user_id
WHERE u.id = $1 AND pc.product_id = $2
`

type GetPriceChangesForUserAndProductParams struct {
	ID        int64 `json:"id"`
	ProductID int64 `json:"product_id"`
}

func (q *Queries) GetPriceChangesForUserAndProduct(ctx context.Context, arg GetPriceChangesForUserAndProductParams) ([]PriceChange, error) {
	rows, err := q.db.Query(ctx, getPriceChangesForUserAndProduct, arg.ID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceChange{}
	for rows.Next() {
		var i PriceChange
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceChangesByProductID = `-- name: ListPriceChangesByProductID :many
SELECT id, product_id, price, created_at FROM price_changes WHERE product_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListPriceChangesByProductIDParams struct {
	ProductID int64 `json:"product_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListPriceChangesByProductID(ctx context.Context, arg ListPriceChangesByProductIDParams) ([]PriceChange, error) {
	rows, err := q.db.Query(ctx, listPriceChangesByProductID, arg.ProductID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceChange{}
	for rows.Next() {
		var i PriceChange
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePriceChange = `-- name: UpdatePriceChange :one
UPDATE price_changes SET price = $2, created_at = $3 WHERE id = $1 RETURNING id, product_id, price, created_at
`

type UpdatePriceChangeParams struct {
	ID        int64     `json:"id"`
	Price     float64   `json:"price"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) UpdatePriceChange(ctx context.Context, arg UpdatePriceChangeParams) (PriceChange, error) {
	row := q.db.QueryRow(ctx, updatePriceChange, arg.ID, arg.Price, arg.CreatedAt)
	var i PriceChange
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}
