// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckUserProduct(ctx context.Context, arg CheckUserProductParams) (Product, error)
	CreatePriceChange(ctx context.Context, arg CreatePriceChangeParams) (PriceChange, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePriceChange(ctx context.Context, id int64) error
	DeleteProduct(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetPriceChangeByID(ctx context.Context, id int64) (PriceChange, error)
	GetPriceChangesByPriceRange(ctx context.Context, arg GetPriceChangesByPriceRangeParams) ([]PriceChange, error)
	GetPriceChangesByTimeRange(ctx context.Context, arg GetPriceChangesByTimeRangeParams) ([]PriceChange, error)
	GetProductByID(ctx context.Context, id int64) (Product, error)
	GetProductByLinkAndUserID(ctx context.Context, arg GetProductByLinkAndUserIDParams) (GetProductByLinkAndUserIDRow, error)
	GetProductsByAveragePrice(ctx context.Context, arg GetProductsByAveragePriceParams) ([]GetProductsByAveragePriceRow, error)
	GetProductsByStore(ctx context.Context, arg GetProductsByStoreParams) ([]Product, error)
	GetProductsByTimeRange(ctx context.Context, arg GetProductsByTimeRangeParams) ([]Product, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, arg GetUserParams) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListPriceChangesByProductID(ctx context.Context, arg ListPriceChangesByProductIDParams) ([]PriceChange, error)
	ListProductsByUserID(ctx context.Context, arg ListProductsByUserIDParams) ([]Product, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	UpdatePriceChange(ctx context.Context, arg UpdatePriceChangeParams) (PriceChange, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
